// localization/en.dart
// English language strings for Memind app.
// Each key represents a UI text element. Add new keys here for new features.

const Map<String, String> en = {
  // App titles and navigation
  'appTitle': 'Memind',
  'settingsTitle': 'Settings',
  'notesTitle': 'Notes',
  'noteDetailTitle': 'Note Detail',
  // Dialogs and actions
  'delete': 'Delete',
  'cancel': 'Cancel',
  'save': 'Save',
  'edit': 'Edit',
  'close': 'Close',
  'add': 'Add',
  'archive': 'Archive',
  'unarchive': 'Unarchive',
  'pin': 'Pin',
  'unpin': 'Unpin',
  'moveToFolder': 'Move to folder',
  'manageFolders': 'Manage folders',
  'newFolder': 'New folder name',
  'renameFolder': 'Rename folder',
  'deleteFolder': 'Delete folder?',
  'noFolders': 'No folders yet',
  'allFolders': 'All folders',
  'noFolder': 'No folder',
  'folders': 'Folders',
  // Confirmations and prompts
  'deleteConfirmTitle': 'Delete note?',
  'deleteConfirmText': 'This action cannot be undone.',
  'dontAskAgain': "Don't ask again",
  'askBeforeDelete': 'Ask before deleting notes',
  'previewBackground': 'Preview background',
  'choose': 'Choose',
  'useDefaultBackground': 'Use default background',
  'invalidPathOrUrl': 'Invalid path or URL',
  'failedToPickImage': 'Failed to pick image',
  'failedToCaptureImage': 'Failed to capture image',
  'cameraNotSupported': 'Camera not supported on web',
  // Search and input
  'searchHint': 'Search notes...',
  'voiceInputNotAvailable': 'Voice input not available',
  'aiSummary': 'AI Summary',
  'openNoteToUseAI': 'Open a note to use AI',
  // Note fields
  'titleHint': 'Title',
  'contentHint': 'Content',
  // Misc
  'language': 'Language',
  'theme': 'Theme',
  'noteView': 'Note view',
  'storage': 'Storage',
  'background': 'Background',
  'default': 'Default',
  'customImage': 'Custom image',
  'card': 'Card',
  'list': 'List',
  'mini': 'Mini',
  'hive': 'Hive',
  'sharedPreferences': 'SharedPreferences',
  'migratedToHive': 'Migrated to Hive storage',
  'migrationFailed': 'Migration failed',
  'usingSharedPreferences': 'Using SharedPreferences',
  'settings': 'Settings',
  'details': 'Details',
  'created': 'Created',
  'updated': 'Updated',
  'id': 'ID',
};
