// localization/tr.dart
// Turkish language strings for Memind app.
// Her anahtar bir arayüz metnini temsil eder. Yeni özellikler için yeni anahtarlar ekleyin.

const Map<String, String> tr = {
  // Uygulama başlıkları ve gezinme
  'appTitle': 'Memind',
  'settingsTitle': 'Ayarlar',
  'notesTitle': 'Notlar',
  'noteDetailTitle': 'Not Detayı',
  // Diyaloglar ve işlemler
  'delete': 'Sil',
  'cancel': 'İptal',
  'save': 'Kaydet',
  'edit': 'Düzenle',
  'close': 'Kapat',
  'add': 'Ekle',
  'archive': 'Arşivle',
  'unarchive': 'Arşivden çıkar',
  'pin': 'Sabitle',
  'unpin': 'Sabitliği kaldır',
  'moveToFolder': 'Klasöre taşı',
  'manageFolders': 'Klasörleri yönet',
  'newFolder': 'Yeni klasör adı',
  'renameFolder': 'Klasörü yeniden adlandır',
  'deleteFolder': 'Klasör silinsin mi?',
  'noFolders': 'Henüz klasör yok',
  'allFolders': 'Tüm klasörler',
  'noFolder': 'Klasörsüz',
  'folders': 'Klasörler',
  // Onaylar ve uyarılar
  'deleteConfirmTitle': 'Not silinsin mi?',
  'deleteConfirmText': 'Bu işlem geri alınamaz.',
  'dontAskAgain': 'Bir daha sorma',
  'askBeforeDelete': 'Silmeden önce sor',
  'previewBackground': 'Arka planı önizle',
  'choose': 'Seç',
  'useDefaultBackground': 'Varsayılan arka planı kullan',
  'invalidPathOrUrl': 'Geçersiz yol veya URL',
  'failedToPickImage': 'Resim seçilemedi',
  'failedToCaptureImage': 'Resim yakalanamadı',
  'cameraNotSupported': 'Web’de kamera desteklenmiyor',
  // Arama ve giriş
  'searchHint': 'Notlarda ara...',
  'voiceInputNotAvailable': 'Sesli giriş kullanılamıyor',
  'aiSummary': 'Yapay Zeka Özeti',
  'openNoteToUseAI': 'Yapay zeka için bir not açın',
  // Not alanları
  'titleHint': 'Başlık',
  'contentHint': 'İçerik',
  // Diğer
  'language': 'Dil',
  'theme': 'Tema',
  'noteView': 'Not görünümü',
  'storage': 'Depolama',
  'background': 'Arka plan',
  'default': 'Varsayılan',
  'customImage': 'Özel resim',
  'card': 'Kart',
  'list': 'Liste',
  'mini': 'Mini',
  'hive': 'Hive',
  'sharedPreferences': 'SharedPreferences',
  'migratedToHive': 'Hive depolamaya geçildi',
  'migrationFailed': 'Geçiş başarısız',
  'usingSharedPreferences': 'SharedPreferences kullanılıyor',
  'settings': 'Ayarlar',
  'details': 'Detaylar',
  'created': 'Oluşturulma',
  'updated': 'Güncellendi',
  'id': 'Kimlik',
};
